@baseUrl = localhost:8080

### Add
POST {{baseUrl}}/add
Content-Type: application/json

{
  "number1": 1,
  "number2": 2
}

### Subtract
POST {{baseUrl}}/subtract
Content-Type: application/json

{
  "number1": 1,
  "number2": 2
}

### Multiply
POST {{baseUrl}}/multiply
Content-Type: application/json

{
  "number1": 1,
  "number2": 2
}

### Divide
POST {{baseUrl}}/divide
Content-Type: application/json

{
  "dividend": 4,
  "divisor": 2
}
